dist: "trusty"
language: python
addons:
    apt:
        packages:
            - "python3"
            - "python3-pip"
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch

# command to install dependencies
before-install:
  - pip install cython
  - pip install pytest-cov
  - pip install coveralls
install:
  - pip install cmc
script:
  - py.test --cov=coinmarketcap-history/
after_success:
  - coveralls
