dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install --upgrade pytest
  - pip install --upgrade pytest-cov
  - pip install coveralls
  - pip install cmc
script:
  - pytest --cov=cms/
after_success:
  - coveralls
